
exports.EMAIL_TEMPLATES = {
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    SIGN_UP: 'SIGN_UP',
    EXCEPTION_EMAIL: 'EXCEPTION_EMAIL',
    INVITING_STUDENT: 'INVITE_STUDENT',
    REINVITING_STUDENT: 'REINVITE_STUDENT',
    REPORTS: 'REPORTS',
};

exports.DEVICE_TYPE = {
    IOS_TYPE_ID: '00000000-0000-0000-0000-000000005002',
    ANDROID_TYPE_ID: '00000000-0000-0000-0000-000000005001',
};

exports.HEADERS = {
    ACCESS_TOKEN: 'access-token',
    AUTH_TOKEN: 'Authorization',
};

const ACCESS_TYPES = {
    PRIVATE: 'PRIVATE',
    PUBLIC: 'PUBLIC',
};

exports.ACCESS_TYPES = ACCESS_TYPES;


const GENDERS = {
    MALE: 'Male',
    FEMALE: 'Female',
    OTHER: 'Other',
};
exports.GENDERS = GENDERS;

