module.exports = Object.freeze({
    MOM_MENTION: 'MOM_MENTION',
    TASK_ASSIGN: 'TASK_ASSIGN',
    PROJECT_ASSIGN: 'PROJECT_ASSIGN',
    COMMENT_MENTION: 'COMMENT_MENTION',
    NEW_COMMENT: 'NEW_COMMENT',
    TEAM_ASSIGN: 'TEAM_ASSIGN',
    TASK_APPROVE_SUCCESS: 'TASK_APPROVE_SUCCESS',
    TASK_APPROVE_FAIL: 'TASK_APPROVE_FAIL',
}); 
